import os
import sqlite3

DATABASE_URL = os.environ.get("DATABASE_URL")
SQLITE_DATABASE = "jewellery.db"


# =========================================================
# POSTGRES COMPATIBILITY WRAPPER
# =========================================================

class PostgresResult:
    def __init__(self, cursor):
        self.cursor = cursor
        self.lastrowid = None

        try:
            if cursor.description:
                columns = [col.name for col in cursor.description]
                rows = cursor.fetchall()

                self.rows = [
                    dict(zip(columns, row))
                    for row in rows
                ]
            else:
                self.rows = []
        except Exception:
            self.rows = []

    def fetchone(self):
        if not self.rows:
            return None

        return self.rows[0]

    def fetchall(self):
        return self.rows


class PostgresConnection:
    def __init__(self, connection):
        self.connection = connection

    def _convert_query(self, query):
        return query.replace("?", "%s")

    def execute(self, query, params=()):
        query = self._convert_query(query)

        cursor = self.connection.cursor()

        # INSERT INTO bills ke liye generated id chahiye
        normalized = " ".join(query.strip().lower().split())

        if normalized.startswith("insert into bills") and "returning id" not in normalized:
            query = query.rstrip().rstrip(";") + " RETURNING id"

            cursor.execute(query, params)

            row = cursor.fetchone()

            result = PostgresResult.__new__(PostgresResult)
            result.cursor = cursor
            result.rows = []
            result.lastrowid = row[0] if row else None

            return result

        cursor.execute(query, params)

        return PostgresResult(cursor)

    def commit(self):
        self.connection.commit()

    def rollback(self):
        self.connection.rollback()

    def close(self):
        self.connection.close()


# =========================================================
# DATABASE CONNECTION
# =========================================================

def get_db_connection():

    # Render / PostgreSQL
    if DATABASE_URL:

        import psycopg

        conn = psycopg.connect(
            DATABASE_URL
        )

        return PostgresConnection(conn)

    # Local / SQLite
    conn = sqlite3.connect(
        SQLITE_DATABASE
    )

    conn.row_factory = sqlite3.Row

    return conn


# =========================================================
# DATABASE TABLES
# =========================================================

def init_db():

    conn = get_db_connection()

    # =====================================================
    # CUSTOMERS
    # =====================================================

    conn.execute("""
        CREATE TABLE IF NOT EXISTS customers (
            id INTEGER PRIMARY KEY
                GENERATED BY DEFAULT AS IDENTITY,
            name TEXT NOT NULL,
            mobile TEXT,
            address TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """ if DATABASE_URL else """
        CREATE TABLE IF NOT EXISTS customers (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            mobile TEXT,
            address TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # =====================================================
    # BILLS
    # =====================================================

    conn.execute("""
        CREATE TABLE IF NOT EXISTS bills (
            id INTEGER PRIMARY KEY
                GENERATED BY DEFAULT AS IDENTITY,
            bill_no TEXT UNIQUE NOT NULL,
            customer_name TEXT,
            customer_mobile TEXT,
            subtotal REAL DEFAULT 0,
            discount REAL DEFAULT 0,
            gst REAL DEFAULT 0,
            grand_total REAL DEFAULT 0,
            payment_mode TEXT,
            amount_paid REAL DEFAULT 0,
            balance REAL DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """ if DATABASE_URL else """
        CREATE TABLE IF NOT EXISTS bills (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            bill_no TEXT UNIQUE NOT NULL,
            customer_name TEXT,
            customer_mobile TEXT,
            subtotal REAL DEFAULT 0,
            discount REAL DEFAULT 0,
            gst REAL DEFAULT 0,
            grand_total REAL DEFAULT 0,
            payment_mode TEXT,
            amount_paid REAL DEFAULT 0,
            balance REAL DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # =====================================================
    # BILL ITEMS
    # =====================================================

    conn.execute("""
        CREATE TABLE IF NOT EXISTS bill_items (
            id INTEGER PRIMARY KEY
                GENERATED BY DEFAULT AS IDENTITY,
            bill_id INTEGER NOT NULL,
            item_name TEXT,
            purity TEXT,
            gross_weight REAL DEFAULT 0,
            stone_weight REAL DEFAULT 0,
            net_weight REAL DEFAULT 0,
            rate REAL DEFAULT 0,
            making REAL DEFAULT 0,
            amount REAL DEFAULT 0,
            FOREIGN KEY (bill_id)
                REFERENCES bills(id)
        )
    """ if DATABASE_URL else """
        CREATE TABLE IF NOT EXISTS bill_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            bill_id INTEGER NOT NULL,
            item_name TEXT,
            purity TEXT,
            gross_weight REAL DEFAULT 0,
            stone_weight REAL DEFAULT 0,
            net_weight REAL DEFAULT 0,
            rate REAL DEFAULT 0,
            making REAL DEFAULT 0,
            amount REAL DEFAULT 0,
            FOREIGN KEY (bill_id)
                REFERENCES bills(id)
        )
    """)

    # =====================================================
    # RATES
    # =====================================================

    conn.execute("""
        CREATE TABLE IF NOT EXISTS rates (
            id INTEGER PRIMARY KEY
                GENERATED BY DEFAULT AS IDENTITY,
            metal TEXT NOT NULL,
            purity TEXT,
            rate REAL DEFAULT 0,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """ if DATABASE_URL else """
        CREATE TABLE IF NOT EXISTS rates (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            metal TEXT NOT NULL,
            purity TEXT,
            rate REAL DEFAULT 0,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # =====================================================
    # PAYMENTS
    # =====================================================

    conn.execute("""
        CREATE TABLE IF NOT EXISTS payments (
            id INTEGER PRIMARY KEY
                GENERATED BY DEFAULT AS IDENTITY,
            bill_id INTEGER NOT NULL,
            customer_mobile TEXT,
            amount REAL DEFAULT 0,
            payment_mode TEXT,
            note TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (bill_id)
                REFERENCES bills(id)
        )
    """ if DATABASE_URL else """
        CREATE TABLE IF NOT EXISTS payments (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            bill_id INTEGER NOT NULL,
            customer_mobile TEXT,
            amount REAL DEFAULT 0,
            payment_mode TEXT,
            note TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (bill_id)
                REFERENCES bills(id)
        )
    """)

    conn.commit()
    conn.close()


if __name__ == "__main__":
    init_db()
    print("Database updated successfully!")